services:
  redmine:
    build: .
    container_name: redmine
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      DATABASE_URL: mysql2://redmine:redmine@db/redmine
      SECRET_KEY_BASE: dc574167cb881dfd1b871dbedba58e11a2130341044b66848a0c71661c3d0e2576e60b05b13914d1dddb2a4d8319cb1b7fc41c824ea27f0c0df3b99959366bfe
    depends_on:
      - db

  db:
    image: mariadb:11
    environment:
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
